#!/bin/sh

unicode_stop

font="$1"

if [ -n "$1" ]; then
  if [ "$1" -le 9 ]; then
    map=0"$1"
  else
    map="$1"
  fi
else
  map=01
  font=1
fi

consolechars -f iso8859-"$font".psf
consolechars -m iso"$map".acm

