#!/bin/sh

unicode_stop

font="$1"

if [ -n "$1" ]; then
  map="$1"
else
  map=1
  font=1
fi

#consolechars -f iso8859-"$font".psf
#consolechars -m iso"$map".acm

setfont iso8859-"$font".psf -m ISO-8859-$map

