.\"                                      Hey, EMACS: -*- nroff -*-
.TH UTF8 1 "2002-08-30"
.SH NAME
utf8 \- quickly change console font and console mode into UTF-8 encoding
.SH SYNOPSIS
.B utf8
.RI [ filename ]
.SH DESCRIPTION
This manual page documents the
.B utf8
command.
.PP
\fButf8\fP is a simple shell script that selects UTF-8 console font 
and switches console into UTF-8 mode.

If no
.I filename
is given, 512 character font LatCyrGr-16.psf font is used, otherwise 
.I filename
is assumed to be a font name to be used.

If 
.I filename
is 2, special 256 character font chavo.psf is used.

.SH AUTHOR
This manual page was written by Radovan Garabík <garabik @ kassiopeia.juls.savba.sk>,
for the fonty-rg package.

.SH COMMENT
This manpage is in UTF-8 encoding. This is intentional.

